dataset_name: 'humaneval'
model_path: "/home/mazhaoyu/projects/llms/GSAI-ML/LLaDA-8B-Instruct"
data_root: "./data"

dataset_config:
  load_dataset_args: { path: "humaneval" }
  problem_file: "./data/humaneval/HumanEval.jsonl"
  problem_file_et: './data/humaneval/HumanEval_ET.jsonl'

generation_args: { gen_length: 256, block_length: 256, temperature: 0.0 }
method: 'saber'